newstory6/urls.py
from django.urls import path
from .views import *

app_name = "newstory6"
urlpatterns = [
    path('', kegiatan, name='kegiatan'),
    path('savekegiatan', savekegiatan, name='savekegiatan'),
    path("saveorang", saveorang, name='saveorang'),
    path('deletekegiatan/<int:myid>',hapuskegiatan,name='hapuskegiatan'),
]

starter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('tugas.urls')),
    path('story1/',include('story1.urls')),
    path('story5/', include('story5.urls')),
    path('story6/', include('newstory6.urls')),
]

tugas/urls.py
from django.urls import path
from .views import *

app_name = "tugas"
urlpatterns = [
    path('',home,name='home'),
    path('about/',about,name='about'),
    path('more/',more,name='more'),
]

newstory6/models.py
from django.db import models

# Create your models here.
class Peserta(models.Model):
    nama = models.CharField(max_length=200)

class ListKegiatan(models.Model):
    nama_kegiatan = models.CharField(max_length=200)
    deskripsi = models.CharField(max_length=200)
    list_orang = models.ManyToManyField(Peserta,blank=True, related_name='orang')

newstory6/forms.py
from django import forms
from .models import *

class detail_kegiatan(forms.ModelForm):
    class Meta:
        model = ListKegiatan
        fields = ['nama_kegiatan', 'deskripsi']
    error_messages = {
        'required' : 'Please Type'
    }
    input_attrs1 = {
        'type' : 'text',
        'placeholder' : 'Nama kegiatan',
        'style' : 'background-color: #E8EEF2'
    }
    input_attrs2 = {
        'type' : 'text',
        'placeholder' : 'Deskripsi kegiatan',
        'style' : 'background-color: #E8EEF2'
    }
    nama_kegiatan = forms.CharField(label='Nama kegiatan', required=True, max_length=27, widget=forms.TextInput(attrs=input_attrs1))
    deskripsi = forms.CharField(label='Deskripsi kegiatan', required=True, max_length=27, widget=forms.Textarea(attrs=input_attrs2))

class nama_orang(forms.ModelForm):
    class Meta:
        model = Peserta
        fields = ['nama']
    error_messages = {
        'required' : 'Please Type'
    }
    input_attrs = {
        'type' : 'text',
        'placeholder' : 'Nama Pendaftar',
        'style' : 'background-color: #E8EEF2'
    }
    nama = forms.CharField(label='Nama pendaftar', required=True, max_length=27, widget=forms.TextInput(attrs=input_attrs))

newstory6/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import *
from .models import *

# Create your views here.
response = {}
def kegiatan(request):
    form1 = detail_kegiatan()
    form2 = nama_orang()
    list_kegiatan = ListKegiatan.objects.all()
    list_orang = Peserta.objects.all()
    response['kegiatan'] = list_kegiatan
    response['orang'] = list_orang
    response['form1'] = form1
    response['form2'] = form2
    return render(request,'Kegiatan.html', response)

def savekegiatan(request):
    form = detail_kegiatan(request.POST or None)
    if (form.is_valid and request.method == 'POST'):
        response['nama_kegiatan'] = request.POST['nama_kegiatan']
        response['deskripsi'] = request.POST['deskripsi']
        list_kegiatan = ListKegiatan(nama_kegiatan=response['nama_kegiatan'], deskripsi=response['deskripsi'],)
        list_kegiatan.save()
        return HttpResponseRedirect('/story6')
    else:
        return HttpResponseRedirect('/')

def saveorang(request):
    form = nama_orang(request.POST or None)
    if (form.is_valid and request.method == 'POST'):
        response['nama'] = request.POST['nama']
        orang = Peserta(nama=response['nama'])
        orang.save()
        return HttpResponseRedirect('/story6')
    else:
        return HttpResponseRedirect('/')

def hapuskegiatan(request, myid):
    ListKegiatan.objects.get(id=myid).delete()
    return HttpResponseRedirect('/story6')

newstory6/templates/Kegiatan.html
{% extends 'base.html' %}
{% load static %}
	{% block content %}
        <div class="card">
		</br>
		<h1 style='text-align: center; color: #0B3954'><b>Form untuk Mengisi Kegiatan</b></h1>
		</br>
	    <div class='row'>
		<div class='col-sm-6'>
	    	    <form action="{% url 'newstory6:savekegiatan' %}" method='POST'>
            		{% csrf_token %}
	    	        <table>
	    		{{ form1.as_table }}
	    	        </table>
			</br>
	    		<input type='submit' value='Submit'>
            	    </form>
            	</div>
		<div class='col-sm-6'>
		    <table style="width:100%; border:1px solid black; background-color: #E8EEF2;">
			<tr>
			    <th style="border:1px solid black">List Kegiatan</th>
			    <th style="border:1px solid black">Peserta</th>
			    <th style="border:1px solid black">Tambah Peserta</th>
			    <th style="border:1px solid black">Hapus</th>
			</tr>
			{% for a in kegiatan %}
			<tr>
	 	            <td style="border:1px solid black">
				<h3>{{ a.nama_kegiatan }}</h3>
				<p>{{ a.deskripsi }}</p>
			    </td>
			    <td style="border:1px solid black">
				    {% for b in a.orang.all %}
					<p>{{ b.nama }}</p>
				    {% endfor %}
			    </td>
		            <td style="border:1px solid black">
	    	    		<form action="{% url 'newstory6:saveorang' %}" method='POST'>
            			    {% csrf_token %}
	    			    {{ form2.as_p }}
				    </br>
	    			<input type='submit' value='Submit'>
            	    		</form>
			    </td>
	  	            <td style="border:1px solid black"><a href="{% url 'newstory6:hapuskegiatan' myid=a.id %}" style='color: black'>Delete</a></td>
			</tr>
			{% endfor %}
		    </table>
	        </div>
		    
            </div>

        </div>
	{% endblock %}